# Copyright 2021 Ross Light
# SPDX-License-Identifier: ISC

name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ["1.16", "1.15"]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -mod=readonly -race -v ./...
